---
name: Tests

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches: [main]

jobs:
  build:

    strategy:
      matrix:
        node-version: [16, 18, 20]
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 7.14.0
          run_install: true
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Test ${{ matrix.node-version }}
        run: npm run coverage
      - name: Coveralls Parallel
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          flag-name: node-${{ matrix.node-version }}
          parallel: true
  finish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          parallel-finished: true
